# Generated by Django 5.0.6 on 2024-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonial', '0002_alter_testimonial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
