# Generated by Django 5.0.6 on 2024-09-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Your_Car_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('title_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('des_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('des_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('add_car_button', models.CharField(blank=True, max_length=60, null=True)),
                ('background_image', models.FileField(blank=True, max_length=200, null=True, upload_to='Add_Your_Car_Section/')),
                ('mobile_background_image', models.FileField(blank=True, max_length=200, null=True, upload_to='Add_Your_Car_Section/')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Add Your Car Section',
            },
        ),
    ]
