# Generated by Django 5.0.6 on 2024-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200, null=True)),
                ('Answer', models.CharField(max_length=700, null=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Payment Questions',
            },
        ),
    ]
