# Generated by Django 5.0.6 on 2024-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Hero_Section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_hero_section',
            old_name='caption',
            new_name='title_1',
        ),
        migrations.AddField(
            model_name='main_hero_section',
            name='title_2',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
