# Generated by Django 5.0.6 on 2024-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Hero_Section', '0002_rename_caption_main_hero_section_title_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_hero_section',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
