# Generated by Django 5.0.6 on 2024-08-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Hero_Section', '0008_alter_main_hero_section_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_hero_section',
            name='car_option',
        ),
    ]
