# Generated by Django 5.0.6 on 2024-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Hero_Section', '0009_remove_main_hero_section_car_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_hero_section',
            options={'verbose_name': '', 'verbose_name_plural': 'Main Hero Section'},
        ),
    ]
