# Generated by Django 5.0.6 on 2024-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Choose_Us_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('feature', models.CharField(max_length=60, null=True)),
                ('icon_code', models.CharField(max_length=60, null=True)),
                ('image', models.FileField(max_length=200, null=True, upload_to='Counter_Section/')),
                ('background_image', models.FileField(max_length=200, null=True, upload_to='Counter_Section/')),
            ],
        ),
    ]
