# Generated by Django 5.0.6 on 2024-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Why_Choose_Us_Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_choose_us_section',
            name='background_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Counter_Section/'),
        ),
        migrations.AlterField(
            model_name='why_choose_us_section',
            name='icon_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='why_choose_us_section',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Counter_Section/'),
        ),
    ]
