# Generated by Django 5.0.6 on 2024-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Why_Choose_Us_Section', '0002_alter_why_choose_us_section_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='why_choose_us_section',
            old_name='feature',
            new_name='feature_1',
        ),
        migrations.RenameField(
            model_name='why_choose_us_section',
            old_name='icon_code',
            new_name='icon_code_1',
        ),
        migrations.AddField(
            model_name='why_choose_us_section',
            name='feature_2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='why_choose_us_section',
            name='feature_3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='why_choose_us_section',
            name='feature_4',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='why_choose_us_section',
            name='icon_code_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='why_choose_us_section',
            name='icon_code_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='why_choose_us_section',
            name='icon_code_4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
