# Generated by Django 5.0.6 on 2024-08-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Why_Choose_Us_Section', '0004_why_choose_us_section_mobile_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='why_choose_us_section',
            old_name='feature_1',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='why_choose_us_section',
            old_name='icon_code_1',
            new_name='icon_code',
        ),
        migrations.RemoveField(
            model_name='why_choose_us_section',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='why_choose_us_section',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='why_choose_us_section',
            name='feature_4',
        ),
        migrations.RemoveField(
            model_name='why_choose_us_section',
            name='icon_code_2',
        ),
        migrations.RemoveField(
            model_name='why_choose_us_section',
            name='icon_code_3',
        ),
        migrations.RemoveField(
            model_name='why_choose_us_section',
            name='icon_code_4',
        ),
    ]
