# Generated by Django 5.0.6 on 2024-08-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Why_Choose_Us_Section', '0006_rename_feature_why_choose_us_section_feature_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_choose_us_section',
            name='background_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Why_Choose_Us_Section/'),
        ),
        migrations.AlterField(
            model_name='why_choose_us_section',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Why_Choose_Us_Section/'),
        ),
        migrations.AlterField(
            model_name='why_choose_us_section',
            name='mobile_background_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Why_Choose_Us_Section/'),
        ),
    ]
