# Generated by Django 5.0.6 on 2024-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Why_Choose_Us_Section', '0007_alter_why_choose_us_section_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='why_choose_us_section',
            options={'verbose_name': '', 'verbose_name_plural': 'Why Choose Us Section'},
        ),
    ]
