# Generated by Django 5.0.6 on 2024-08-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(max_length=300, null=True, upload_to='products/'),
        ),
    ]
