# Generated by Django 5.0.6 on 2024-08-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Your_Drive_Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_your_drive',
            options={'verbose_name': '', 'verbose_name_plural': 'Book Your Drive'},
        ),
    ]
