# Generated by Django 5.0.6 on 2024-08-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('number_of_feature', models.CharField(max_length=60, null=True)),
                ('sign_of_feature', models.CharField(max_length=2, null=True)),
                ('feature', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
