# Generated by Django 5.0.6 on 2024-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter_Section', '0002_alter_counter_section_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter_section',
            options={'verbose_name': '', 'verbose_name_plural': 'Counter Section'},
        ),
    ]
