# Generated by Django 5.0.6 on 2024-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choose_Car_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_option', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
