# Generated by Django 5.0.6 on 2024-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
