# Generated by Django 5.0.6 on 2024-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0002_cars_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': '', 'verbose_name_plural': 'Our Cars'},
        ),
    ]

