# Generated by Django 5.0.6 on 2024-08-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_cars_feature_1_alter_cars_feature_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.FileField(max_length=200, null=True, upload_to='Cars/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='passengers',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
