# Generated by Django 5.0.6 on 2024-08-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_alter_cars_image_alter_cars_passengers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'My Custom Name',
                'verbose_name_plural': 'My Custom Name',
            },
        ),
    ]
