# Generated by Django 5.0.6 on 2024-08-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'My Custom Name', 'verbose_name_plural': 'My Custom Name'},
        ),
    ]
