# Generated by Django 5.0.6 on 2024-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0004_rename_title_cars_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='stock',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
