# Generated by Django 5.0.6 on 2024-09-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0005_cars_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='stock',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
