# Generated by Django 5.0.6 on 2024-08-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_alter_cars_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': '', 'verbose_name_plural': 'OUR CARS'},
        ),
    ]
