# Generated by Django 5.0.6 on 2024-08-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0008_alter_cars_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_image_1',
            new_name='carousel_image',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='feature_1',
            new_name='features_left',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='feature_2',
            new_name='features_right',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_image_2',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_image_3',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_image_4',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='feature_4',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='feature_5',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='feature_6',
        ),
    ]
