# Generated by Django 5.0.6 on 2024-09-08 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0008_alter_cars_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='stock',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
