# Generated by Django 5.0.6 on 2024-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0009_rename_car_image_1_cars_carousel_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='carousel_image',
            new_name='car_image_1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='features_left',
            new_name='feature_1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='features_right',
            new_name='feature_2',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image_2',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image_3',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image_4',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature_4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature_5',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature_6',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
