# Generated by Django 5.0.6 on 2024-09-16 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0010_alter_cars_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Cars/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='passengers',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='stock',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
