# Generated by Django 5.0.6 on 2024-09-16 09:19

import Header.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', validators=[Header.models.validate_image_format])),
                ('link1_name', models.CharField(blank=True, max_length=15)),
                ('link1', models.CharField(blank=True, max_length=60)),
                ('link2_name', models.CharField(blank=True, max_length=15)),
                ('link2', models.CharField(blank=True, max_length=60)),
                ('link3_name', models.CharField(blank=True, max_length=15)),
                ('link3', models.CharField(blank=True, max_length=60)),
                ('link4_name', models.CharField(blank=True, max_length=15)),
                ('link4', models.CharField(blank=True, max_length=60)),
                ('link5_name', models.CharField(blank=True, max_length=15)),
                ('link5', models.CharField(blank=True, max_length=60)),
                ('side_navigation_image', models.ImageField(upload_to='images/', validators=[Header.models.validate_image_format])),
                ('side_navigation_description', models.CharField(blank=True, max_length=60)),
                ('side_navigation_heading', models.CharField(blank=True, max_length=15)),
                ('side_navigation_location', models.CharField(blank=True, max_length=100)),
                ('side_navigation_email', models.CharField(blank=True, max_length=100)),
                ('side_navigation_phone', models.CharField(blank=True, help_text='Enter a valid phone number.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '03999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('side_navigation_schedule', models.CharField(blank=True, max_length=200)),
                ('side_navigation_facebook_link', models.CharField(blank=True, max_length=300)),
                ('side_navigation_twitter_link', models.CharField(blank=True, max_length=300)),
                ('side_navigation_instagram_link', models.CharField(blank=True, max_length=300)),
                ('side_navigation_youtube_link', models.CharField(blank=True, max_length=300)),
                ('side_navigation_rights', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Header',
            },
        ),
    ]
