# Generated by Django 5.0.6 on 2024-09-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='image',
            new_name='header_logo',
        ),
    ]
