# Generated by Django 5.0.6 on 2024-09-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0002_rename_image_header_header_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='link1',
            field=models.URLField(),
        ),
    ]
