# Generated by Django 5.0.6 on 2024-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0003_alter_header_link1'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='link1',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
