# Generated by Django 5.0.6 on 2024-09-16 21:58

import Header.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0005_remove_header_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to='images/', validators=[Header.models.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='header',
            name='side_navigation_image',
            field=models.ImageField(blank=True, upload_to='images/', validators=[Header.models.validate_image_format]),
        ),
    ]
