# Generated by Django 5.0.6 on 2024-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0008_header_dropdownlinks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='link6',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='header',
            name='link6_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='header',
            name='link7',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='header',
            name='link7_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
