# Generated by Django 5.0.6 on 2024-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0009_header_link6_header_link6_name_header_link7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='side_navigation_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
