# Generated by Django 5.0.6 on 2024-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Cars_Carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_cars_carousel',
            options={'verbose_name': '', 'verbose_name_plural': 'Main Cars Carousel'},
        ),
    ]
