# Generated by Django 5.0.6 on 2024-09-16 15:17

import Main_Cars_Carousel.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Cars_Carousel', '0002_alter_main_cars_carousel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_cars_carousel',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='Main_Cars_Carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), Main_Cars_Carousel.validators.validate_image_dimensions]),
        ),
    ]
