# Generated by Django 5.0.6 on 2024-09-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Background_Video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='background_video',
            name='download_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
