# Generated by Django 5.0.6 on 2024-09-08 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quick_book',
            name='pickupdate',
        ),
        migrations.RemoveField(
            model_name='quick_book',
            name='returndate',
        ),
        migrations.AddField(
            model_name='quick_book',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='quick_book',
            name='phone',
            field=models.CharField(help_text='Enter a valid phone number.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
