# Generated by Django 5.0.6 on 2024-09-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0004_alter_quick_book_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick_book',
            name='car',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
