# Generated by Django 5.0.6 on 2024-09-09 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0005_alter_quick_book_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick_book',
            name='car',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='quick_book',
            name='phone',
            field=models.CharField(help_text='Enter a valid phone number.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '03999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
