# Generated by Django 5.0.6 on 2024-09-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0007_alter_quick_book_car_alter_quick_book_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quick_book',
            options={'verbose_name': '', 'verbose_name_plural': 'Quick Booking'},
        ),
    ]
