# Generated by Django 5.0.6 on 2024-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0008_alter_quick_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick_book',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
