# Generated by Django 5.0.6 on 2024-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0009_alter_quick_book_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_book',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quick_book',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
