# Generated by Django 5.0.6 on 2024-09-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Book', '0010_quick_book_message_alter_quick_book_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quick_book',
            name='message',
        ),
    ]
