# Generated by Django 5.0.6 on 2024-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Default_Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=200, null=True, upload_to='Default_Background/')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Default Background',
            },
        ),
    ]
