# Generated by Django 5.0.6 on 2024-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_background',
            name='About_Page_Title_1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='default_background',
            name='About_Page_Title_2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='default_background',
            name='About_Page_description_1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='default_background',
            name='About_Page_description_2',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
