# Generated by Django 5.0.6 on 2024-09-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0002_default_background_about_page_title_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_background',
            name='About_Page_Title_1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='About_Page_description_1',
            field=models.TextField(max_length=100),
        ),
    ]
