# Generated by Django 5.0.6 on 2024-09-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0006_default_background_blog_page_title_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_background',
            name='Contact_Page_Title_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='default_background',
            name='Contact_Page_description_1',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
