# Generated by Django 5.0.6 on 2024-09-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0007_default_background_contact_page_title_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_background',
            name='Create_Account_Page_Title_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='default_background',
            name='Login_Page_Title_1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='default_background',
            name='Login_Page_Title_2',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
