# Generated by Django 5.0.6 on 2024-09-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0009_default_background_car_details_page_title_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_background',
            name='Blog_Page_description_2',
        ),
        migrations.RemoveField(
            model_name='default_background',
            name='Login_Page_Title_2',
        ),
        migrations.AlterField(
            model_name='default_background',
            name='About_Page_Title_1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='About_Page_description_1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Blog_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Blog_Page_description_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Car_Details_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Car_Details_Page_description_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Cars_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Cars_Page_description_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Contact_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Contact_Page_description_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Create_Account_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Faq_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Faq_Page_description_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Login_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Team_Page_Title_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='default_background',
            name='Team_Page_description_1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
