# Generated by Django 5.0.6 on 2024-09-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0010_remove_default_background_blog_page_description_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_background',
            name='Faq_Page_Title_2',
        ),
        migrations.RemoveField(
            model_name='default_background',
            name='Faq_Page_description_2',
        ),
    ]
