# Generated by Django 5.0.6 on 2024-09-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0011_remove_default_background_faq_page_title_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_background',
            name='Add_Your_Car_Page_Title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
