# Generated by Django 5.0.6 on 2024-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Default_Background', '0012_default_background_add_your_car_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_background',
            name='Bookings_Page_Title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
