# Generated by Django 5.0.6 on 2024-09-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='footer_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='footer_logo',
            new_name='logo',
        ),
    ]
