# Generated by Django 5.0.6 on 2024-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Counter_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.CharField(max_length=600, null=True)),
                ('description_2', models.CharField(max_length=600, null=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'About Description',
            },
        ),
    ]
